<h3>Importamos las bibliotecas</h3>
<p>
    <ol>
        <li>Numpy</li>
    <ol/>
</p>

In [3]:
import numpy as np

In [14]:
#Creamos nuestra función, que arroje un error si la lista contiene menos de 9 elementos, y hacemos un reshape() convertir la lista en una matriz en la forma 3 X 3
#Aplicamos las forumlas para calcular Media, Varianza, Desviación estándar, Máx, Mín, Sum, de los ejes respectivos.  
def calculate(list):
  if len(list)<9:
    raise ValueError(f"List must contain nine numbers.")
  list=np.array(list)
  list=list.reshape(3,3)
  print("3 X 3 Matrix:") 
  print(list)


 
  calculations={
    'mean': [list.mean(axis=0).tolist(),list.mean(axis=1).tolist(),list.mean()],
    'variance': [list.var(axis=0).tolist(),list.var(axis=1).tolist(),list.var()],
    'standard deviation': [list.std(axis=0).tolist(),list.std(axis=1).tolist(),list.std()],
    'max': [list.max(axis=0).tolist(),list.max(axis=1).tolist(),list.max()],
    'min': [list.min(axis=0).tolist(),list.min(axis=1).tolist(),list.min()],
    'sum': [list.sum(axis=0).tolist(),list.sum(axis=1).tolist(),list.sum()]
    }
  return calculations

In [15]:
calculate([0,1,2,3,4,5,6,7,8])

3 X 3 Matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'variance': [[6.0, 6.0, 6.0],
  [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
  6.666666666666667],
 'standard deviation': [[2.449489742783178,
   2.449489742783178,
   2.449489742783178],
  [0.816496580927726, 0.816496580927726, 0.816496580927726],
  2.581988897471611],
 'max': [[6, 7, 8], [2, 5, 8], 8],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'sum': [[9, 12, 15], [3, 12, 21], 36]}